name: pipeline

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  workflow_dispatch:

jobs:
  build-job:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run : sudo apt update && sudo apt install -y firefox
      - run: firefox -v

  test-job:
    runs-on: ubuntu.latest
    steps:
      - uses: actions/checkout@v3
      - run : firefox index.html

  deploy-job:
    runs-on: ubuntu.latest
    steps:
      - uses: actions/checkout@v3
      - run : echo "finalizado"
  
    
  
