name: pipeline

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  workflow_dispatch:

jobs:
  build-job:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: sudo apt-get update && sudo apt-get install firefox xvfb -y
      - run: sudo apt-get install -y libgtk-3-0 libdbus-glib-1-2
      
      
  test-job:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: |
          export MOZ_DISABLE_OOP_PLUGINS=1
          export MOZ_DISABLE_GPU=1
      - run: xvfb-run --auto-servernum firefox --headless --no-remote --disable-gpu --disable-gl-drawing --disable-gl-renderer --disable-webgl index.html

  deploy-job:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run : echo "finalizado"
  
    
  
